export interface Player {
    id: string;
    name: string;
    role: "Batsman" | "Bowler" | "Allrounder" | "Wicketkeeper";
    consistency: number;
    form: number;
    isOverseasPlayer?: boolean;
    bowlerType?: "Pace" | "Spin";
    arType?: "Batting" | "Bowling";
    mat: number;
    isCaptain?: boolean; // Add this field
  }
  
  export interface Team {
    id: string
    name: string
    shortName: string
    color: string
    players: Player[]
  }
  export const teams: Team[] = [
    {
      id: "csk",
      name: "Chennai Super Kings",
      shortName: "CSK",
      color: "#FFFF00",
      players: [
        {
          id: "csk-1",
          name: "RD Gaikwad",
          role: "Batsman",
          consistency: 344.27,
          form: 109.46,
          isOverseasPlayer: false,
          mat: 66,
          isCaptain: true,
        },
        {
          id: "csk-2",
          name: "DP Conway",
          role: "Batsman",
          consistency: 153.91,
          form: 120.68,
          isOverseasPlayer: true,
          mat: 23,
        },
        {
          id: "csk-3",
          name: "R Ravindra",
          role: "Allrounder",
          consistency: 22.96,
          form: 25.42,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 10,
        },
        {
          id: "csk-4",
          name: "V Shankar",
          role: "Allrounder",
          consistency: 4.84,
          form: 3.85,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 72,
        },
        {
          id: "csk-5",
          name: "RA Tripathi",
          role: "Batsman",
          consistency: 322.65,
          form: 52.95,
          isOverseasPlayer: false,
          mat: 95,
        },
        {
          id: "csk-6",
          name: "S Dube",
          role: "Allrounder",
          consistency: 110.46,
          form: 42.02,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 65,
        },
        {
          id: "csk-7",
          name: "DJ Hooda",
          role: "Allrounder",
          consistency: 106.66,
          form: 17.66,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 118,
        },
        {
          id: "csk-8",
          name: "V Bedi",
          role: "Wicketkeeper",
          consistency: 0,
          form: 0,
          isOverseasPlayer: false,
          mat: 1,
        },
        {
          id: "csk-9",
          name: "SM Curran",
          role: "Allrounder",
          consistency: 85.72,
          form: 32.91,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 59,
        },
        {
          id: "csk-10",
          name: "J Overton",
          role: "Allrounder",
          consistency: 28.01,
          form: 21.41,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 18,
        },
        {
          id: "csk-11",
          name: "MS Dhoni",
          role: "Wicketkeeper",
          consistency: 730.30,
          form: 72.53,
          isOverseasPlayer: false,
          mat: 264,
        },
        {
          id: "csk-12",
          name: "RS Ghosh",
          role: "Allrounder",
          consistency: -1.87,
          form: 6.21,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 6,
        },
        {
          id: "csk-13",
          name: "RA Jadeja",
          role: "Allrounder",
          consistency: 256.42,
          form: 34.20,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 240,
        },
        {
          id: "csk-14",
          name: "SK Rasheed",
          role: "Batsman",
          consistency: 51.10,
          form: 18.38,
          isOverseasPlayer: false,
          mat: 17,
        },
        {
          id: "csk-15",
          name: "R Ashwin",
          role: "Allrounder",
          consistency: 122.58,
          form: 17.99,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 212,
        },
        {
          id: "csk-16",
          name: "NT Ellis",
          role: "Bowler",
          consistency: -1.99,
          form: -3.58,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 16,
        },
        {
          id: "csk-17",
          name: "S Gopal",
          role: "Bowler",
          consistency: 7.90,
          form: -3.32,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 52,
        },
        {
          id: "csk-18",
          name: "A Kamboj",
          role: "Bowler",
          consistency: -12.75,
          form: -8.39,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 3,
        },
        {
          id: "csk-19",
          name: "KL Nagarkoti",
          role: "Allrounder",
          consistency: 5.29,
          form: 6.45,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 12,
        },
        {
          id: "csk-20",
          name: "Noor Ahmad",
          role: "Bowler",
          consistency: -0.15,
          form: 13.21,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          mat: 23,
        },
        {
          id: "csk-21",
          name: "KK Ahmed",
          role: "Bowler",
          consistency: -2.00,
          form: 0.69,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 57,
        },
        {
          id: "csk-22",
          name: "Gurjapneet Singh",
          role: "Bowler",
          consistency: -1.76,
          form: -0.57,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 5,
        },
        {
          id: "csk-23",
          name: "M Pathirana",
          role: "Bowler",
          consistency: 4.72,
          form: 1.59,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 20,
        },
        {
          id: "csk-24",
          name: "Mukesh Choudhary",
          role: "Bowler",
          consistency: -2.70,
          form: -17.32,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 14,
        },
      ],
    },
    {
      id: "dc",
      name: "Delhi Capitals",
      shortName: "DC",
      color: "#00008B",
      players: [
        {
          id: "dc-1",
          name: "KL Rahul",
          role: "Wicketkeeper",
          consistency: 649.92,
          form: 97.13,
          isOverseasPlayer: false,
          mat: 132,
        },
        {
          id: "dc-2",
          name: "J Fraser-McGurk",
          role: "Batsman",
          consistency: 89.05,
          form: 94.09,
          isOverseasPlayer: true,
          mat: 9,
        },
        {
          id: "dc-3",
          name: "F du Plessis",
          role: "Batsman",
          consistency: 63.41,
          form: 91.94,
          isOverseasPlayer: true,
          mat: 145,
        },
        {
          id: "dc-4",
          name: "KK Nair",
          role: "Batsman",
          consistency: 20.08,
          form: 51.30,
          isOverseasPlayer: false,
          mat: 87,
        },
        {
          id: "dc-5",
          name: "Abishek Porel",
          role: "Batsman",
          consistency: 77.46,
          form: 77.76,
          isOverseasPlayer: false,
          mat: 18,
        },
        {
          id: "dc-6",
          name: "HC Brook",
          role: "Batsman",
          consistency: 49.56,
          form: 51.30,
          isOverseasPlayer: true,
          mat: 11,
        },
        {
          id: "dc-7",
          name: "T Stubbs",
          role: "Batsman",
          consistency: 89.39,
          form: 93.63,
          isOverseasPlayer: true,
          mat: 18,
        },
        {
          id: "dc-8",
          name: "V Nigam",
          role: "Allrounder",
          consistency: 11.37,
          form: 12.59,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 7,
        },
        {
          id: "dc-9",
          name: "AR Sharma",
          role: "Batsman",
          consistency: 57.75,
          form: 60.41,
          isOverseasPlayer: false,
          mat: 11,
        },
        {
          id: "dc-10",
          name: "Sameer Rizvi",
          role: "Batsman",
          consistency: 28.89,
          form: 31.21,
          isOverseasPlayer: false,
          mat: 8,
        },
        {
          id: "dc-11",
          name: "AR Patel",
          role: "Allrounder",
          consistency: 159.52,
          form: 31.28,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 150,
          isCaptain: true,
        },
        {
          id: "dc-12",
          name: "AJ Mandal",
          role: "Allrounder",
          consistency: 31.02,
          form: 16.12,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 46,
        },
        {
          id: "dc-13",
          name: "D Ferreira",
          role: "Batsman",
          consistency: 14.12,
          form: 15.59,
          isOverseasPlayer: true,
          mat: 2,
        },
        {
          id: "dc-14",
          name: "T Vijay",
          role: "Allrounder",
          consistency: 7.23,
          form: -7.63,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 8,
        },
        {
          id: "dc-15",
          name: "L Manvanth Kumar",
          role: "Allrounder",
          consistency: 2.62,
          form: -6.18,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 3,
        },
        {
          id: "dc-16",
          name: "MA Starc",
          role: "Bowler",
          consistency: 8.41,
          form: 0.73,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 41,
        },
        {
          id: "dc-17",
          name: "PVD Chameera",
          role: "Bowler",
          consistency: -8.64,
          form: -15.38,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 13,
        },
        {
          id: "dc-18",
          name: "DG Nalkande",
          role: "Allrounder",
          consistency: 8.36,
          form: 0.28,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 6,
        },
        {
          id: "dc-19",
          name: "Kuldeep Yadav",
          role: "Bowler",
          consistency: 17.31,
          form: 1.12,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 84,
        },
        {
          id: "dc-20",
          name: "MM Sharma",
          role: "Bowler",
          consistency: 30.12,
          form: -1.54,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 112,
        },
        {
          id: "dc-21",
          name: "T Natarajan",
          role: "Bowler",
          consistency: 40.24,
          form: 1.93,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 61,
        },
        {
          id: "dc-22",
          name: "Mukesh Kumar",
          role: "Bowler",
          consistency: -0.82,
          form: 1.31,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 20,
        },
      ],
    },
    {
      id: "gt",
      name: "Gujarat Titans",
      shortName: "GT",
      color: "#00008B",
      players: [
        {
          id: "gt-1",
          name: "Karim Janat",
          role: "Allrounder",
          consistency: 31.43,
          form: 17.98,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 0,
        },
        {
          id: "gt-2",
          name: "N Sindhu",
          role: "Allrounder",
          consistency: 27.27,
          form: 17.07,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 22,
        },
        {
          id: "gt-3",
          name: "MK Lomror",
          role: "Allrounder",
          consistency: 39.47,
          form: 19.71,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 40,
        },
        {
          id: "gt-4",
          name: "M Shahrukh Khan",
          role: "Allrounder",
          consistency: 42.71,
          form: 19.49,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 40,
        },
        {
          id: "gt-5",
          name: "R Tewatia",
          role: "Allrounder",
          consistency: 88.24,
          form: 21.97,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 93,
        },
        {
          id: "gt-6",
          name: "Washington Sundar",
          role: "Allrounder",
          consistency: 45.85,
          form: 4.77,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 60,
        },
        {
          id: "gt-7",
          name: "J Yadav",
          role: "Allrounder",
          consistency: 12.44,
          form: 9.99,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 20,
        },
        {
          id: "gt-8",
          name: "R Sai Kishore",
          role: "Allrounder",
          consistency: 20.47,
          form: 22.66,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 10,
        },
        {
          id: "gt-9",
          name: "Arshad Khan",
          role: "Allrounder",
          consistency: 18.22,
          form: 16.69,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 10,
        },
        {
          id: "gt-10",
          name: "JC Buttler",
          role: "Wicketkeeper",
          consistency: 504.31,
          form: 79.10,
          isOverseasPlayer: true,
          mat: 107,
        },
        {
          id: "gt-11",
          name: "GD Phillips",
          role: "Batsman",
          consistency: 30.15,
          form: 40.21,
          isOverseasPlayer: true,
          mat: 8,
        },
        {
          id: "gt-12",
          name: "SE Rutherford",
          role: "Batsman",
          consistency: 33.88,
          form: 19.26,
          isOverseasPlayer: true,
          mat: 10,
        },
        {
          id: "gt-13",
          name: "Shubman Gill",
          role: "Batsman",
          consistency: 454.43,
          form: 87.96,
          isOverseasPlayer: false,
          mat: 103,
          isCaptain: true,
        },
        {
          id: "gt-14",
          name: "Anuj Rawat",
          role: "Wicketkeeper",
          consistency: 65.55,
          form: 40.79,
          isOverseasPlayer: false,
          mat: 24,
        },
        {
          id: "gt-15",
          name: "B Sai Sudharsan",
          role: "Batsman",
          consistency: 167.59,
          form: 100.75,
          isOverseasPlayer: false,
          mat: 25,
        },
        {
          id: "gt-16",
          name: "K Kushagra",
          role: "Batsman",
          consistency: 7.86,
          form: 8.79,
          isOverseasPlayer: false,
          mat: 4,
        },
        {
          id: "gt-17",
          name: "Rashid Khan",
          role: "Bowler",
          consistency: 35.69,
          form: 12.61,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          mat: 121,
        },
        {
          id: "gt-18",
          name: "G Coetzee",
          role: "Bowler",
          consistency: -3.20,
          form: -0.53,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 10,
        },
        {
          id: "gt-19",
          name: "K Rabada",
          role: "Bowler",
          consistency: 26.75,
          form: 0.98,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 80,
        },
        {
          id: "gt-20",
          name: "MJ Suthar",
          role: "Bowler",
          consistency: -22.40,
          form: -14.86,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 1,
        },
        {
          id: "gt-21",
          name: "Mohammed Siraj",
          role: "Bowler",
          consistency: 18.32,
          form: 0.60,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 93,
        },
        {
          id: "gt-22",
          name: "I Sharma",
          role: "Bowler",
          consistency: 17.30,
          form: -1.55,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 110,
        },
        {
          id: "gt-23",
          name: "Gurnoor Brar",
          role: "Bowler",
          consistency: -22.55,
          form: -15.03,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 1,
        },
        {
          id: "gt-24",
          name: "M Prasidh Krishna",
          role: "Bowler",
          consistency: 5.23,
          form: 1.51,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 51,
        },
        {
          id: "gt-25",
          name: "K Khejroliya",
          role: "Bowler",
          consistency: -9.04,
          form: -5.80,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 7,
        },
      ],
    },
    {
      id: "kkr",
      name: "Kolkata Knight Riders",
      shortName: "KKR",
      color: "#800080",
      players: [
        {
          id: "kkr-1",
          name: "MM Ali",
          role: "Allrounder",
          consistency: 40.25,
          form: 20.50,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 67,
        },
        {
          id: "kkr-2",
          name: "AD Russell",
          role: "Allrounder",
          consistency: 209.63,
          form: 87.25,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 127,
        },
        {
          id: "kkr-3",
          name: "Ramandeep Singh",
          role: "Allrounder",
          consistency: 26.39,
          form: 23.12,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 20,
        },
        {
          id: "kkr-4",
          name: "AS Roy",
          role: "Allrounder",
          consistency: -9.92,
          form: -12.64,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 11,
        },
        {
          id: "kkr-5",
          name: "Q de Kock",
          role: "Wicketkeeper",
          consistency: 443.95,
          form: 61.57,
          isOverseasPlayer: true,
          mat: 107,
        },
        {
          id: "kkr-6",
          name: "Rahmanullah Gurbaz",
          role: "Wicketkeeper",
          consistency: 64.14,
          form: 38.87,
          isOverseasPlayer: true,
          mat: 14,
        },
        {
          id: "kkr-7",
          name: "R Powell",
          role: "Batsman",
          consistency: 75.46,
          form: 45.03,
          isOverseasPlayer: true,
          mat: 27,
        },
        {
          id: "kkr-8",
          name: "AM Rahane",
          role: "Batsman",
          consistency: 637.67,
          form: 57.00,
          isOverseasPlayer: false,
          mat: 185,
          isCaptain: true,
        },
        {
          id: "kkr-9",
          name: "MK Pandey",
          role: "Batsman",
          consistency: 33.86,
          form: 37.91,
          isOverseasPlayer: false,
          mat: 171,
        },
        {
          id: "kkr-10",
          name: "A Raghuvanshi",
          role: "Batsman",
          consistency: 51.41,
          form: 54.24,
          isOverseasPlayer: false,
          mat: 10,
        },
        {
          id: "kkr-11",
          name: "LS Sisodia",
          role: "Wicketkeeper",
          consistency: 28.01,
          form: 25.93,
          isOverseasPlayer: false,
          mat: 15,
        },
        {
          id: "kkr-12",
          name: "VR Iyer",
          role: "Batsman",
          consistency: 204.04,
          form: 85.76,
          isOverseasPlayer: false,
          mat: 51,
        },
        {
          id: "kkr-13",
          name: "RK Singh",
          role: "Batsman",
          consistency: 147.87,
          form: 52.63,
          isOverseasPlayer: false,
          mat: 46,
        },
        {
          id: "kkr-14",
          name: "SP Narine",
          role: "Bowler",
          consistency: 43.72,
          form: 1.94,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          mat: 177,
        },
        {
          id: "kkr-15",
          name: "A Nortje",
          role: "Bowler",
          consistency: 9.86,
          form: -5.15,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 46,
        },
        {
          id: "kkr-16",
          name: "SH Johnson",
          role: "Bowler",
          consistency: -7.95,
          form: -4.93,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 5,
        },
        {
          id: "kkr-17",
          name: "M Markande",
          role: "Bowler",
          consistency: -3.08,
          form: -3.31,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 37,
        },
        {
          id: "kkr-18",
          name: "CV Varun",
          role: "Bowler",
          consistency: 16.92,
          form: 3.36,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 71,
        },
        {
          id: "kkr-19",
          name: "Umran Malik",
          role: "Bowler",
          consistency: -10.33,
          form: -15.21,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 26,
        },
        {
          id: "kkr-20",
          name: "Harshit Rana",
          role: "Bowler",
          consistency: 0.85,
          form: 2.40,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 21,
        },
        {
          id: "kkr-21",
          name: "VG Arora",
          role: "Bowler",
          consistency: -2.39,
          form: -0.93,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 20,
        },
      ],
    },
    {
      id: "lsg",
      name: "Lucknow Super Giants",
      shortName: "LSG",
      color: "#00008B",
      players: [
        {
          id: "lsg-1",
          name: "MR Marsh",
          role: "Allrounder",
          consistency: 62.72,
          form: 14.25,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 42,
        },
        {
          id: "lsg-2",
          name: "MP Breetzke",
          role: "Batsman",
          consistency: 57.62,
          form: 13.94,
          isOverseasPlayer: true,
          mat: 28,
        },
        {
          id: "lsg-3",
          name: "AK Markram",
          role: "Batsman",
          consistency: 158.53,
          form: 54.97,
          isOverseasPlayer: true,
          mat: 44,
        },
        {
          id: "lsg-4",
          name: "AA Kulkarni",
          role: "Batsman",
          consistency: 20.98,
          form: 23.56,
          isOverseasPlayer: false,
          mat: 2,
        },
        {
          id: "lsg-5",
          name: "N Pooran",
          role: "Wicketkeeper",
          consistency: 266.78,
          form: 108.16,
          isOverseasPlayer: true,
          mat: 76,
        },
        {
          id: "lsg-6",
          name: "Himmat Singh",
          role: "Batsman",
          consistency: 104.56,
          form: 43.07,
          isOverseasPlayer: false,
          mat: 55,
        },
        {
          id: "lsg-7",
          name: "A Juyal",
          role: "Wicketkeeper",
          consistency: 65.56,
          form: 41.72,
          isOverseasPlayer: false,
          mat: 23,
        },
        {
          id: "lsg-8",
          name: "Y Chaudhary",
          role: "Allrounder",
          consistency: 32.51,
          form: 21.66,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 15,
        },
        {
          id: "lsg-9",
          name: "RR Pant",
          role: "Wicketkeeper",
          consistency: 464.23,
          form: 92.90,
          isOverseasPlayer: false,
          mat: 111,
          isCaptain: true,
        },
        {
          id: "lsg-10",
          name: "A Badoni",
          role: "Batsman",
          consistency: 111.11,
          form: 60.80,
          isOverseasPlayer: false,
          mat: 42,
        },
        {
          id: "lsg-11",
          name: "Shahbaz Ahmed",
          role: "Allrounder",
          consistency: 49.66,
          form: 26.97,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 55,
        },
        {
          id: "lsg-12",
          name: "DA Miller",
          role: "Batsman",
          consistency: 418.93,
          form: 61.40,
          isOverseasPlayer: true,
          mat: 130,
        },
        {
          id: "lsg-13",
          name: "Abdul Samad",
          role: "Allrounder",
          consistency: 47.14,
          form: 15.41,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 50,
        },
        {
          id: "lsg-14",
          name: "RS Hangargekar",
          role: "Bowler",
          consistency: -4.68,
          form: -3.10,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 2,
        },
        {
          id: "lsg-15",
          name: "Ravi Bishnoi",
          role: "Bowler",
          consistency: 10.26,
          form: 2.88,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 66,
        },
        {
          id: "lsg-16",
          name: "DS Rathi",
          role: "Bowler",
          consistency: -0.44,
          form: -0.01,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 2,
        },
        {
          id: "lsg-17",
          name: "M Siddharth",
          role: "Bowler",
          consistency: -15.35,
          form: -9.90,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 3,
        },
        {
          id: "lsg-18",
          name: "S Joseph",
          role: "Bowler",
          consistency: -22.20,
          form: -14.64,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 1,
        },
        {
          id: "lsg-19",
          name: "Mohsin Khan",
          role: "Bowler",
          consistency: 1.11,
          form: -3.14,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 24,
        },
        {
          id: "lsg-20",
          name: "Akash Deep",
          role: "Bowler",
          consistency: -9.04,
          form: -9.23,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 8,
        },
        {
          id: "lsg-21",
          name: "Prince Yadav",
          role: "Bowler",
          consistency: -3.19,
          form: -1.12,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 8,
        },
        {
          id: "lsg-22",
          name: "MP Yadav",
          role: "Bowler",
          consistency: -1.51,
          form: -0.23,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 4,
        },
        {
          id: "lsg-23",
          name: "Akash Singh",
          role: "Bowler",
          consistency: -9.31,
          form: -4.66,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 7,
        },
        {
          id: "lsg-24",
          name: "Avesh Khan",
          role: "Bowler",
          consistency: 13.66,
          form: 1.34,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 63,
        },
      ],
    },
    {
      id: "mi",
      name: "Mumbai Indians",
      shortName: "MI",
      color: "#00008B",
      players: [
        {
          id: "mi-1",
          name: "WG Jacks",
          role: "Allrounder",
          consistency: 28.52,
          form: 31.28,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 8,
        },
        {
          id: "mi-2",
          name: "MJ Santner",
          role: "Allrounder",
          consistency: 16.27,
          form: 7.53,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 18,
        },
        {
          id: "mi-3",
          name: "Naman Dhir",
          role: "Allrounder",
          consistency: 18.46,
          form: 21.42,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 7,
        },
        {
          id: "mi-4",
          name: "NT Tilak Varma",
          role: "Allrounder",
          consistency: 83.80,
          form: 37.31,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 38,
        },
        {
          id: "mi-5",
          name: "HH Pandya",
          role: "Allrounder",
          consistency: 197.66,
          form: 69.18,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 137,
          isCaptain: true,
        },
        {
          id: "mi-6",
          name: "RD Rickelton",
          role: "Wicketkeeper",
          consistency: 16.04,
          form: 29.74,
          isOverseasPlayer: true,
          mat: 25,
        },
        {
          id: "mi-7",
          name: "BJ Jacobs",
          role: "Batsman",
          consistency: 14.38,
          form: 16.79,
          isOverseasPlayer: true,
          mat: 3,
        },
        {
          id: "mi-8",
          name: "RG Sharma",
          role: "Batsman",
          consistency: 901.24,
          form: 87.81,
          isOverseasPlayer: false,
          mat: 257,
        },
        {
          id: "mi-9",
          name: "SA Yadav",
          role: "Batsman",
          consistency: 505.25,
          form: 82.32,
          isOverseasPlayer: false,
          mat: 150,
        },
        {
          id: "mi-10",
          name: "RA Bawa",
          role: "Batsman",
          consistency: 15.69,
          form: 17.37,
          isOverseasPlayer: false,
          mat: 2,
        },
        {
          id: "mi-11",
          name: "KL Shrijith",
          role: "Wicketkeeper",
          consistency: 14.58,
          form: 7.60,
          isOverseasPlayer: false,
          mat: 17,
        },
        {
          id: "mi-12",
          name: "R Minz",
          role: "Wicketkeeper",
          consistency: 29.63,
          form: 22.36,
          isOverseasPlayer: false,
          mat: 7,
        },
        {
          id: "mi-13",
          name: "TA Boult",
          role: "Bowler",
          consistency: 27.01,
          form: 0.56,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 104,
        },
        {
          id: "mi-14",
          name: "RJW Topley",
          role: "Bowler",
          consistency: -7.60,
          form: -5.78,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 5,
        },
        {
          id: "mi-15",
          name: "Mujeeb Ur Rahman",
          role: "Bowler",
          consistency: 0.84,
          form: 1.90,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          mat: 0,
        },
        {
          id: "mi-16",
          name: "LB Williams",
          role: "Bowler",
          consistency: -16.18,
          form: -10.74,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 2,
        },
        {
          id: "mi-17",
          name: "DL Chahar",
          role: "Bowler",
          consistency: 14.42,
          form: -4.79,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 81,
        },
        {
          id: "mi-18",
          name: "KV Sharma",
          role: "Bowler",
          consistency: 13.17,
          form: -8.94,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 84,
        },
        {
          id: "mi-19",
          name: "Ashwani Kumar",
          role: "Bowler",
          consistency: -7.20,
          form: -4.81,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 4,
        },
        {
          id: "mi-20",
          name: "JJ Bumrah",
          role: "Bowler",
          consistency: 40.13,
          form: 3.67,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 133,
        },
        {
          id: "mi-21",
          name: "AS Tendulkar",
          role: "Bowler",
          consistency: -8.27,
          form: -14.22,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 5,
        },
        {
          id: "mi-22",
          name: "PVSN Raju",
          role: "Bowler",
          consistency: -3.06,
          form: -1.51,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 7,
        },
      ],
    },
    {
      id: "pbks",
      name: "Punjab Kings",
      shortName: "PBKS",
      color: "#FF0000",
      players: [
        {
          id: "pbks-1",
          name: "Azmatullah Omarzai",
          role: "Allrounder",
          consistency: 11.64,
          form: 13.85,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 7,
        },
        {
          id: "pbks-2",
          name: "GJ Maxwell",
          role: "Allrounder",
          consistency: 206.98,
          form: 15.15,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 134,
        },
        {
          id: "pbks-3",
          name: "MP Stoinis",
          role: "Allrounder",
          consistency: 146.01,
          form: 40.30,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 96,
        },
        {
          id: "pbks-4",
          name: "AM Hardie",
          role: "Allrounder",
          consistency: 64.68,
          form: 7.59,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 61,
        },
        {
          id: "pbks-5",
          name: "M Jansen",
          role: "Allrounder",
          consistency: 16.80,
          form: 8.12,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 21,
        },
        {
          id: "pbks-6",
          name: "P Arya",
          role: "Allrounder",
          consistency: 37.49,
          form: 24.56,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 18,
        },
        {
          id: "pbks-7",
          name: "Shashank Singh",
          role: "Allrounder",
          consistency: 41.49,
          form: 41.57,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 24,
        },
        {
          id: "pbks-8",
          name: "Suryansh Shedge",
          role: "Allrounder",
          consistency: 21.11,
          form: 21.87,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 9,
        },
        {
          id: "pbks-9",
          name: "Harpreet Brar",
          role: "Allrounder",
          consistency: 33.29,
          form: 21.06,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 41,
        },
        {
          id: "pbks-10",
          name: "P Dubey",
          role: "Allrounder",
          consistency: 3.48,
          form: 8.78,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 4,
        },
        {
          id: "pbks-11",
          name: "JP Inglis",
          role: "Wicketkeeper",
          consistency: 183.08,
          form: 24.88,
          isOverseasPlayer: true,
          mat: 78,
        },
        {
          id: "pbks-12",
          name: "Prabhsimran Singh",
          role: "Wicketkeeper",
          consistency: 127.50,
          form: 76.87,
          isOverseasPlayer: false,
          mat: 34,
        },
        {
          id: "pbks-13",
          name: "Harnoor Singh",
          role: "Batsman",
          consistency: 16.32,
          form: 12.79,
          isOverseasPlayer: false,
          mat: 6,
        },
        {
          id: "pbks-14",
          name: "SS Iyer",
          role: "Batsman",
          consistency: 439.85,
          form: 79.33,
          isOverseasPlayer: false,
          mat: 116,
          isCaptain: true,
        },
        {
          id: "pbks-15",
          name: "P Avinash",
          role: "Batsman",
          consistency: 23.81,
          form: 5.29,
          isOverseasPlayer: false,
          mat: 5,
        },
        {
          id: "pbks-16",
          name: "N Wadhera",
          role: "Batsman",
          consistency: 73.49,
          form: 41.54,
          isOverseasPlayer: false,
          mat: 20,
        },
        {
          id: "pbks-17",
          name: "Vishnu Vinod",
          role: "Batsman",
          consistency: 25.53,
          form: 29.48,
          isOverseasPlayer: false,
          mat: 6,
        },
        {
          id: "pbks-18",
          name: "XC Bartlett",
          role: "Bowler",
          consistency: 7.02,
          form: -0.61,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 49,
        },
        {
          id: "pbks-19",
          name: "LH Ferguson",
          role: "Bowler",
          consistency: 5.10,
          form: -2.26,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 45,
        },
        {
          id: "pbks-20",
          name: "Yash Thakur",
          role: "Bowler",
          consistency: -0.62,
          form: -2.67,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 19,
        },
        {
          id: "pbks-21",
          name: "V Vyshak",
          role: "Bowler",
          consistency: -4.11,
          form: -4.71,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 11,
        },
        {
          id: "pbks-22",
          name: "Arshdeep Singh",
          role: "Bowler",
          consistency: 14.23,
          form: 1.46,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 65,
        },
        {
          id: "pbks-23",
          name: "KR Sen",
          role: "Bowler",
          consistency: -3.13,
          form: -2.17,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 12,
        },
        {
          id: "pbks-24",
          name: "YS Chahal",
          role: "Bowler",
          consistency: 51.00,
          form: 0.71,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 160,
        },
      ],
    },
    {
      id: "rcb",
      name: "Royal Challengers Bangalore",
      shortName: "RCB",
      color: "#FF0000",
      players: [
        {
          id: "rcb-1",
          name: "PD Salt",
          role: "Wicketkeeper",
          consistency: 121.42,
          form: 97.86,
          isOverseasPlayer: true,
          mat: 21,
        },
        {
          id: "rcb-2",
          name: "SS Chikara",
          role: "Batsman",
          consistency: 8.69,
          form: 9.55,
          isOverseasPlayer: false,
          mat: 4,
        },
        {
          id: "rcb-3",
          name: "V Kohli",
          role: "Batsman",
          consistency: 1087.27,
          form: 133.66,
          isOverseasPlayer: false,
          mat: 252,
        },
        {
          id: "rcb-4",
          name: "D Padikkal",
          role: "Batsman",
          consistency: 120.82,
          form: 19.24,
          isOverseasPlayer: false,
          mat: 64,
        },
        {
          id: "rcb-5",
          name: "RM Patidar",
          role: "Batsman",
          consistency: 138.07,
          form: 88.99,
          isOverseasPlayer: false,
          mat: 27,
          isCaptain: true,
        },
        {
          id: "rcb-6",
          name: "LS Livingstone",
          role: "Allrounder",
          consistency: 77.72,
          form: 21.39,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 39,
        },
        {
          id: "rcb-7",
          name: "JM Sharma",
          role: "Wicketkeeper",
          consistency: 124.92,
          form: 51.12,
          isOverseasPlayer: false,
          mat: 40,
        },
        {
          id: "rcb-8",
          name: "MS Bhandage",
          role: "Allrounder",
          consistency: 16.14,
          form: 7.69,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 28,
        },
        {
          id: "rcb-9",
          name: "TH David",
          role: "Batsman",
          consistency: 120.98,
          form: 65.44,
          isOverseasPlayer: true,
          mat: 38,
        },
        {
          id: "rcb-10",
          name: "R Shepherd",
          role: "Allrounder",
          consistency: 20.73,
          form: 22.69,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 10,
        },
        {
          id: "rcb-11",
          name: "KH Pandya",
          role: "Allrounder",
          consistency: 145.63,
          form: 22.82,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 127,
        },
        {
          id: "rcb-12",
          name: "Swapnil Singh",
          role: "Allrounder",
          consistency: 12.81,
          form: 20.61,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 14,
        },
        {
          id: "rcb-13",
          name: "B Kumar",
          role: "Bowler",
          consistency: 43.73,
          form: 33.87,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 176,
        },
        {
          id: "rcb-14",
          name: "N Thushara",
          role: "Bowler",
          consistency: -15.78,
          form: -12.95,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 7,
        },
        {
          id: "rcb-15",
          name: "Rasikh Salam",
          role: "Bowler",
          consistency: -6.72,
          form: -2.52,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 11,
        },
        {
          id: "rcb-16",
          name: "L Ngidi",
          role: "Bowler",
          consistency: 2.16,
          form: -3.14,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 14,
        },
        {
          id: "rcb-17",
          name: "Suyash Sharma",
          role: "Bowler",
          consistency: -6.08,
          form: -14.81,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 13,
        },
        {
          id: "rcb-18",
          name: "Yash Dayal",
          role: "Bowler",
          consistency: -0.39,
          form: -0.28,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 28,
        },
        {
          id: "rcb-19",
          name: "JR Hazlewood",
          role: "Bowler",
          consistency: 3.83,
          form: -3.51,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 27,
        },
        {
          id: "rcb-20",
          name: "Mohit Rathee",
          role: "Bowler",
          consistency: -22.63,
          form: -15.12,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 1,
        },
      ],
    },
    {
      id: "rr",
      name: "Rajasthan Royals",
      shortName: "RR",
      color: "#FF0000",
      players: [
        {
          id: "rr-1",
          name: "N Rana",
          role: "Allrounder",
          consistency: 186.78,
          form: 14.97,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 107,
        },
        {
          id: "rr-2",
          name: "R Parag",
          role: "Allrounder",
          consistency: 85.50,
          form: 48.24,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Bowling",
          mat: 70,
        },
        {
          id: "rr-3",
          name: "Yudhvir Singh",
          role: "Allrounder",
          consistency: -11.28,
          form: -12.96,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 5,
        },
        {
          id: "rr-4",
          name: "SO Hetmyer",
          role: "Batsman",
          consistency: 197.31,
          form: 49.73,
          isOverseasPlayer: true,
          mat: 72,
        },
        {
          id: "rr-5",
          name: "YBK Jaiswal",
          role: "Batsman",
          consistency: 242.17,
          form: 90.97,
          isOverseasPlayer: false,
          mat: 53,
        },
        {
          id: "rr-6",
          name: "SV Samson",
          role: "Wicketkeeper",
          consistency: 611.28,
          form: 104.84,
          isOverseasPlayer: false,
          mat: 168,
          isCaptain: true,
        },
        {
          id: "rr-7",
          name: "V Suryavanshi",
          role: "Batsman",
          consistency: 28.32,
          form: 1.71,
          isOverseasPlayer: false,
          mat: 1,
        },
        {
          id: "rr-8",
          name: "KS Rathore",
          role: "Wicketkeeper",
          consistency: 44.29,
          form: 45.00,
          isOverseasPlayer: false,
          mat: 12,
        },
        {
          id: "rr-9",
          name: "DC Jurel",
          role: "Batsman",
          consistency: 75.85,
          form: 55.34,
          isOverseasPlayer: false,
          mat: 28,
        },
        {
          id: "rr-10",
          name: "SB Dubey",
          role: "Batsman",
          consistency: 36.44,
          form: 40.24,
          isOverseasPlayer: false,
          mat: 4,
        },
        {
          id: "rr-11",
          name: "PW Hasaranga",
          role: "Bowler",
          consistency: 7.91,
          form: -4.64,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          mat: 26,
        },
        {
          id: "rr-12",
          name: "JC Archer",
          role: "Bowler",
          consistency: 7.22,
          form: -12.90,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 40,
        },
        {
          id: "rr-13",
          name: "Fazalhaq Farooqi",
          role: "Bowler",
          consistency: -7.35,
          form: -3.73,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 7,
        },
        {
          id: "rr-14",
          name: "KT Maphaka",
          role: "Bowler",
          consistency: -20.09,
          form: -13.40,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 2,
        },
        {
          id: "rr-15",
          name: "M Theekshana",
          role: "Bowler",
          consistency: -0.64,
          form: -9.58,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          mat: 27,
        },
        {
          id: "rr-16",
          name: "K Kartikeya",
          role: "Bowler",
          consistency: -5.16,
          form: -5.45,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 12,
        },
        {
          id: "rr-17",
          name: "TU Deshpande",
          role: "Bowler",
          consistency: -4.14,
          form: -11.21,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 36,
        },
        {
          id: "rr-18",
          name: "A Madhwal",
          role: "Bowler",
          consistency: -0.62,
          form: -5.33,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 13,
        },
        {
          id: "rr-19",
          name: "Sandeep Sharma",
          role: "Bowler",
          consistency: 31.37,
          form: 0.11,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 127,
        },
      ],
    },
    {
      id: "srh",
      name: "Sunrisers Hyderabad",
      shortName: "SRH",
      color: "#FF8C00",
      players: [
        {
          id: "srh-1",
          name: "Abhishek Sharma",
          role: "Allrounder",
          consistency: 106.12,
          form: 51.93,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          arType: "Batting",
          mat: 63,
        },
        {
          id: "srh-2",
          name: "TM Head",
          role: "Batsman",
          consistency: 137.43,
          form: 116.98,
          isOverseasPlayer: true,
          mat: 25,
        },
        {
          id: "srh-3",
          name: "A Taide",
          role: "Batsman",
          consistency: 61.80,
          form: 42.67,
          isOverseasPlayer: false,
          mat: 9,
        },
        {
          id: "srh-4",
          name: "Ishan Kishan",
          role: "Wicketkeeper",
          consistency: 375.06,
          form: 73.17,
          isOverseasPlayer: false,
          mat: 105,
        },
        {
          id: "srh-5",
          name: "K Nitish Kumar Reddy",
          role: "Allrounder",
          consistency: 29.79,
          form: 32.63,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 15,
        },
        {
          id: "srh-6",
          name: "H Klaasen",
          role: "Wicketkeeper",
          consistency: 166.11,
          form: 99.33,
          isOverseasPlayer: true,
          mat: 35,
        },
        {
          id: "srh-7",
          name: "Sachin Baby",
          role: "Batsman",
          consistency: 193.59,
          form: 41.75,
          isOverseasPlayer: false,
          mat: 83,
        },
        {
          id: "srh-8",
          name: "A Manohar",
          role: "Batsman",
          consistency: 55.36,
          form: 12.74,
          isOverseasPlayer: false,
          mat: 19,
        },
        {
          id: "srh-9",
          name: "BA Carse",
          role: "Allrounder",
          consistency: 15.88,
          form: 10.98,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          arType: "Batting",
          mat: 0,
        },
        {
          id: "srh-10",
          name: "PJ Cummins",
          role: "Allrounder",
          consistency: 64.78,
          form: 27.28,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 58,
          isCaptain: true,
        },
        {
          id: "srh-11",
          name: "HV Patel",
          role: "Allrounder",
          consistency: 62.07,
          form: 11.81,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          arType: "Bowling",
          mat: 106,
        },
        {
          id: "srh-12",
          name: "Zeeshan Ansari",
          role: "Bowler",
          consistency: -14.05,
          form: -9.08,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          mat: 1,
        },
        {
          id: "srh-13",
          name: "E Malinga",
          role: "Bowler",
          consistency: -14.68,
          form: -9.79,
          isOverseasPlayer: true,
          bowlerType: "Pace",
          mat: 1,
        },
        {
          id: "srh-14",
          name: "Simarjeet Singh",
          role: "Bowler",
          consistency: -4.62,
          form: -2.98,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 10,
        },
        {
          id: "srh-15",
          name: "Mohammed Shami",
          role: "Bowler",
          consistency: 28.34,
          form: 5.95,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 110,
        },
        {
          id: "srh-16",
          name: "JD Unadkat",
          role: "Bowler",
          consistency: 19.51,
          form: -4.00,
          isOverseasPlayer: false,
          bowlerType: "Pace",
          mat: 105,
        },
        {
          id: "srh-17",
          name: "A Zampa",
          role: "Bowler",
          consistency: 2.97,
          form: -1.62,
          isOverseasPlayer: true,
          bowlerType: "Spin",
          mat: 20,
        },
        {
          id: "srh-18",
          name: "RD Chahar",
          role: "Bowler",
          consistency: 13.74,
          form: -1.59,
          isOverseasPlayer: false,
          bowlerType: "Spin",
          mat: 78,
        },
      ],
    },
    // Add more teams as needed
  ]
  
  export const getAllTeams = () => {
    return teams
  }
  
  export const getTeamById = (id: string) => {
    return teams.find((team) => team.id === id)
  }
  
  export const getPlayersByTeam = (teamId: string) => {
    const team = teams.find((team) => team.id === teamId)
    return team ? team.players : []
  }
  
  export const getPlayerById = (teamId: string, playerId: string) => {
    const team = teams.find((team) => team.id === teamId)
    if (!team) return null
    return team.players.find((player) => player.id === playerId)
  }